### PR TITLE
A few updates to make the code more in-line with ROS 2 guidelines.

### PR DESCRIPTION
**Pull request by pgold**
* CreateDriver derives from rclcpp::Node.
* Node::now is used instead of rclcpp::Clock::now.
* Use generic rclcpp::spin instead of CreateDriver having it's own spin loop.

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM!

There's some conflicts (I think with one of your other PRs). Can you resolve it?

**Comment by pgold** [comment]
Thanks for reviewing.

Sure thing! I was just waiting for the other PRs to be merged so that I can rebase and test this one.

**Comment by pgold** [comment]
Rebased and tested.

**Review by jacobperron — APPROVED** [review]

**Comment by jacobperron** [comment]
@pgold If you'd like, feel free to open a PR adding yourself to the "Contributors" list in the README: https://github.com/AutonomyLab/create_robot/tree/foxy#contributors

Thanks for the porting effort!

**Pull request merged**
