### PR TITLE
Cliff sensor foxy

### PR DESCRIPTION
**Pull request by owen7900**
I have implemented the cliff sensor here. I have tested it on a Create2 robot. Backporting to melodic would be annoying for me to do as I don't have an 18.04 install handy, but I could do it if required.

### CODE REVIEW

**Comment by owen7900** [comment]
This fixes #22

**Comment by eborghi10** [comment]
@owen7900 you should modify the feature list of the main README file: https://github.com/AutonomyLab/create_robot/blob/melodic/README.md#features

**Comment by jacobperron** [comment]
Cool, thanks! Changes look alright to me on the first pass. I'll try it out sometime this week on a robot :+1:

**Review by jacobperron — APPROVED** [review]

**Comment by jacobperron** [comment]
Thanks for the contribution!

I squashed merged this manually on `foxy` due to a Git conflict ([c8de6c8](https://github.com/AutonomyLab/create_robot/commit/c8de6c8c70c804b2a6a56acb5efb55c74032a820))

**Pull request closed without merging**
